require "test_helper"

# The static pages Rails serves on errors (generated by script/error_pages.rb).
class ErrorPagesTest < ActiveSupport::TestCase
  test "every error page is in French and links back to the app" do
    pages = Dir[Rails.public_path.join("{400,404,406-unsupported-browser,422,500}.html")]
    assert_equal 5, pages.size
    pages.each do |file|
      html = File.read(file)
      assert_includes html, '<html lang="fr">', file
      assert_includes html, 'href="/maps"', file
      assert_no_match(/We're sorry|doesn't exist|was rejected|not supported|Bad Request/, html, file)
    end
  end
end
